### ISSUE TITLE
Putting the website online

### ISSUE THREAD

**Issue by ReynoldNoynay** [ReynoldNoynay/euro-just-doing-semantics#1]
@mackenzierose  
Getting a message error from markbot that my website is not online?
what is the next step for this?

thank you.

**Comment by ReynoldNoynay** [comment]
@hellachella
Getting a message error from markbot that my website is not online?
what is the next step for this?

thank you.

**Comment by hellachella** [comment]
Assignment complete and graded manually.

**Comment by MacKenzieRose** [comment]
It looks like it's working on my end @ReynoldNoynay 

You can check out the link here: https://reynoldnoynay.github.io/euro-just-doing-semantics/ 😄 

MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄
